-- PostgreSQL Database Schema
SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);

-- Estructura de la tabla 'persona'
CREATE TABLE public.persona (
    id bigint NOT NULL,
    direccion character varying(255),
    edad integer,
    genero character varying(255),
    identificacion character varying(255),
    nombre character varying(255),
    telefono character varying(255)
);

-- Estructura de la tabla 'cliente'
CREATE TABLE public.cliente (
    cliente_id character varying(255) NOT NULL,
    contrasena character varying(255),
    estado character varying(255),
    id bigint NOT NULL
);

-- Estructura de la tabla 'cuenta'
CREATE TABLE public.cuenta (
    id bigint NOT NULL,
    estado character varying(255) NOT NULL,
    numero_cuenta character varying(255) NOT NULL,
    saldo_disponible numeric(38,2) NOT NULL,
    saldo_inicial numeric(38,2) NOT NULL,
    tipo_cuenta character varying(255) NOT NULL,
    cliente_id bigint NOT NULL
);

ALTER TABLE public.cuenta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuenta_id_seq
    START WITH 1
    INCREMENT BY 1
);

-- Estructura de la tabla 'movimiento'
CREATE TABLE public.movimiento (
    id bigint NOT NULL,
    fecha timestamp(6) without time zone NOT NULL,
    saldo numeric(38,2) NOT NULL,
    saldo_inicial numeric(38,2) NOT NULL,
    tipo_movimiento character varying(255),
    valor numeric(38,2) NOT NULL,
    cuenta_id bigint NOT NULL
);

ALTER TABLE public.movimiento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimiento_id_seq
    START WITH 1
    INCREMENT BY 1
);

-- Secuencia para persona
CREATE SEQUENCE public.persona_seq
    START WITH 1
    INCREMENT BY 50;

-- Constraints y Llaves Primarias
ALTER TABLE ONLY public.persona ADD CONSTRAINT persona_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.cliente ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.cliente ADD CONSTRAINT ukkou3iuyp26clwwj9m5d0e6t0l UNIQUE (cliente_id);
ALTER TABLE ONLY public.cuenta ADD CONSTRAINT cuenta_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.cuenta ADD CONSTRAINT ukpj7ncg765kt4klndu25bwbwe4 UNIQUE (numero_cuenta);
ALTER TABLE ONLY public.movimiento ADD CONSTRAINT movimiento_pkey PRIMARY KEY (id);

-- Llaves Foráneas (Foreign Keys)
ALTER TABLE ONLY public.cliente ADD CONSTRAINT fkkpvkbjg32bso6riqge70hwcel FOREIGN KEY (id) REFERENCES public.persona(id);
ALTER TABLE ONLY public.cuenta ADD CONSTRAINT fk4p224uogyy5hmxvn8fwa2jlug FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);
ALTER TABLE ONLY public.movimiento ADD CONSTRAINT fk4ea11fe7p3xa1kwwmdgi9f2fi FOREIGN KEY (cuenta_id) REFERENCES public.cuenta(id);
