-- PostgreSQL Database Schema
SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);

-- Estructura de la tabla 'cuenta'
CREATE TABLE public.cuenta (
    saldo_disponible numeric(38,2) NOT NULL,
    saldo_inicial numeric(38,2) NOT NULL,
    cliente_id bigint NOT NULL,
    id bigint NOT NULL,
    estado character varying(255) NOT NULL,
    numero_cuenta character varying(255) NOT NULL,
    tipo_cuenta character varying(255) NOT NULL
);

ALTER TABLE public.cuenta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuenta_id_seq
    START WITH 1
    INCREMENT BY 1
);

-- Estructura de la tabla 'movimiento'
CREATE TABLE public.movimiento (
    saldo numeric(38,2) NOT NULL,
    saldo_inicial numeric(38,2) NOT NULL,
    valor numeric(38,2) NOT NULL,
    cuenta_id bigint NOT NULL,
    fecha timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    tipo_movimiento character varying(255)
);

ALTER TABLE public.movimiento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimiento_id_seq
    START WITH 1
    INCREMENT BY 1
);

-- Constraints y Llaves Primarias
ALTER TABLE ONLY public.cuenta ADD CONSTRAINT cuenta_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.cuenta ADD CONSTRAINT cuenta_numero_cuenta_key UNIQUE (numero_cuenta);
ALTER TABLE ONLY public.movimiento ADD CONSTRAINT movimiento_pkey PRIMARY KEY (id);

-- Llaves Foráneas (Foreign Keys)
ALTER TABLE ONLY public.movimiento ADD CONSTRAINT fk4ea11fe7p3xa1kwwmdgi9f2fi FOREIGN KEY (cuenta_id) REFERENCES public.cuenta(id);
